-- Copyright (c) 2016-present, Facebook, Inc.
-- All rights reserved.
--
-- This source code is licensed under the BSD-style license found in the
-- LICENSE file in the root directory of this source tree. An additional grant
-- of patent rights can be found in the PATENTS file in the same directory.

-----------------------------------------------------------------
-- Auto-generated by regenClassifiers
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
module Duckling.Ranking.Classifiers.HE_XX (classifiers) where
import Data.String
import Prelude
import qualified Data.HashMap.Strict as HashMap
import Duckling.Ranking.Types

classifiers :: Classifiers
classifiers
  = HashMap.fromList
      [("\1502\1512\1509",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer (numeric)",
        Classifier{okData =
                     ClassData{prior = -1.041453874828161, unseen = -3.4657359027997265,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 30},
                   koData =
                     ClassData{prior = -0.4353180712578455, unseen = -4.04305126783455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 55}}),
       ("\1489 <date>",
        Classifier{okData =
                     ClassData{prior = -0.262364264467491, unseen = -4.127134385045092,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1502\1512\1509", -3.012261575505202),
                                    ("<time> <part-of-day>", -3.417726683613366),
                                    ("mm/dd", -3.417726683613366),
                                    ("intersect", -3.012261575505202), ("day", -2.164963715117998),
                                    ("time-of-day (latent)", -3.012261575505202),
                                    ("<time-of-day> am|pm", -3.417726683613366),
                                    ("named-day", -3.012261575505202),
                                    ("current <day-of-week>", -3.417726683613366),
                                    ("last <time>", -3.417726683613366),
                                    ("\1488\1493\1511\1496\1493\1489\1512", -3.417726683613366),
                                    ("hour", -1.7129785913749407), ("month", -2.501435951739211),
                                    ("\1508\1489\1512\1493\1488\1512", -3.417726683613366),
                                    ("<named-month> <day-of-month> (non ordinal)",
                                     -3.417726683613366),
                                    ("week-end", -3.012261575505202),
                                    ("this <time>", -3.012261575505202)],
                               n = 20},
                   koData =
                     ClassData{prior = -1.466337068793427, unseen = -3.5263605246161616,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.3978952727983707),
                                    ("<time> <part-of-day>", -2.803360380906535),
                                    ("intersect", -2.803360380906535), ("day", -2.3978952727983707),
                                    ("this <cycle>", -2.803360380906535),
                                    ("<day-of-month> (ordinal)", -2.803360380906535),
                                    ("hour", -2.803360380906535), ("month", -2.803360380906535),
                                    ("last <cycle>", -2.803360380906535),
                                    ("this <time>", -2.803360380906535)],
                               n = 6}}),
       ("integer (20..90)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time> <part-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.6286086594223742,
                               unseen = -3.4657359027997265,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayhour", -1.6422277352570913),
                                    ("\1489 <date>morning", -2.740840023925201),
                                    ("hourhour", -2.0476928433652555),
                                    ("todaythis evening", -2.740840023925201),
                                    ("time-of-day (latent)morning", -2.740840023925201),
                                    ("named-daymorning", -2.740840023925201),
                                    ("todayevening|night", -2.740840023925201),
                                    ("at <time-of-day>morning", -2.740840023925201),
                                    ("tomorrowevening|night", -2.3353749158170367)],
                               n = 8},
                   koData =
                     ClassData{prior = -0.7621400520468967,
                               unseen = -3.4011973816621555,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayhour", -1.7578579175523736),
                                    ("time-of-day (latent)this morning", -2.6741486494265287),
                                    ("yesterdayevening|night", -2.6741486494265287),
                                    ("hourhour", -1.9810014688665833),
                                    ("<day-of-month> (ordinal)morning", -2.6741486494265287),
                                    ("\1489 <date>this morning", -2.6741486494265287),
                                    ("at <time-of-day>this morning", -2.6741486494265287),
                                    ("tomorrownoon", -2.268683541318364)],
                               n = 7}}),
       ("today",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("at hour <time-of-day>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1}}),
       ("mm/dd",
        Classifier{okData =
                     ClassData{prior = -1.0986122886681098,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4}}),
       ("at <time-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.2876820724517809,
                               unseen = -2.3025850929940455,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -1.0986122886681098),
                                    ("<time-of-day> am|pm", -1.5040773967762742),
                                    ("hour", -0.8109302162163288)],
                               n = 3},
                   koData =
                     ClassData{prior = -1.3862943611198906, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.916290731874155),
                                    ("hour", -0.916290731874155)],
                               n = 1}}),
       ("<day-of-month> (non ordinal) of <named-month>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.0910424533583156,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)\1502\1512\1509", -1.9459101490553135),
                                    ("integer (numeric)\1508\1489\1512\1493\1488\1512",
                                     -1.4350845252893227),
                                    ("integer (numeric)\1488\1508\1512\1497\1500",
                                     -2.3513752571634776),
                                    ("integer 3\1502\1512\1509", -2.3513752571634776),
                                    ("month", -0.8472978603872037)],
                               n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("absorption of , after named day",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.6931471805599453),
                                    ("named-day", -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("the ides of <named-month>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1502\1512\1509", -0.6931471805599453),
                                    ("month", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinal 4",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3}}),
       ("\1489 <named-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.6931471805599453),
                                    ("named-day", -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("month (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hour (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinal 9",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("integer 21..99 (with and)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods =
                                 HashMap.fromList [("integer (20..90)integer 4", 0.0)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("intersect",
        Classifier{okData =
                     ClassData{prior = -0.3964152725882465, unseen = -4.770684624465665,
                               likelihoods =
                                 HashMap.fromList
                                   [("hourday", -2.5649493574615367),
                                    ("dayhour", -4.069026754237811),
                                    ("monthyear", -3.6635616461296463),
                                    ("\1488\1493\1511\1496\1493\1489\1512year", -4.069026754237811),
                                    ("intersect<time-of-day> am|pm", -4.069026754237811),
                                    ("<time> <part-of-day>\1489 <named-day>", -3.3758795736778655),
                                    ("intersect by \",\"<time-of-day> am|pm", -3.152736022363656),
                                    ("last <day-of-week> of <time>year", -4.069026754237811),
                                    ("dayday", -2.816263785742443), ("dayyear", -2.277267285009756),
                                    ("<day-of-month>(ordinal) <named-month>year",
                                     -3.6635616461296463),
                                    ("\1489 <date>\1489 <named-day>", -4.069026754237811),
                                    ("absorption of , after named day<named-month> <day-of-month> (non ordinal)",
                                     -4.069026754237811),
                                    ("todaythis evening", -4.069026754237811),
                                    ("absorption of , after named day<day-of-month> (ordinal) of <named-month>",
                                     -4.069026754237811),
                                    ("<day-of-month> (ordinal) of <named-month>year",
                                     -3.3758795736778655),
                                    ("named-daynext <cycle>", -4.069026754237811),
                                    ("dayminute", -2.68273239311792),
                                    ("named-day<day-of-month> (ordinal) of <named-month>",
                                     -4.069026754237811),
                                    ("absorption of , after named dayintersect",
                                     -4.069026754237811),
                                    ("named-day<day-of-month> (non ordinal) of <named-month>",
                                     -4.069026754237811),
                                    ("absorption of , after named dayintersect by \",\"",
                                     -3.6635616461296463),
                                    ("year<time-of-day> am|pm", -4.069026754237811),
                                    ("\1489 <date>\1489 <date>", -4.069026754237811),
                                    ("<day-of-month> (non ordinal) of <named-month>year",
                                     -3.3758795736778655),
                                    ("absorption of , after named day<day-of-month> (non ordinal) of <named-month>",
                                     -4.069026754237811),
                                    ("dayweek", -4.069026754237811),
                                    ("\1502\1512\1509year", -4.069026754237811),
                                    ("<time> <part-of-day>\1489 <date>", -3.3758795736778655),
                                    ("<day-of-month> (non ordinal) <named-month>year",
                                     -3.6635616461296463),
                                    ("yearminute", -4.069026754237811)],
                               n = 37},
                   koData =
                     ClassData{prior = -1.1169614273363062, unseen = -4.382026634673881,
                               likelihoods =
                                 HashMap.fromList
                                   [("in <named-month>year", -3.676300671907076),
                                    ("daymonth", -2.9831534913471307),
                                    ("monthyear", -2.5776883832389665),
                                    ("intersecthh:mm", -3.676300671907076),
                                    ("intersect by \",\"hh:mm", -2.760009940032921),
                                    ("hourhour", -3.676300671907076),
                                    ("\1488\1508\1512\1497\1500year", -3.676300671907076),
                                    ("named-dayin <named-month>", -3.676300671907076),
                                    ("at <time-of-day>this morning", -3.676300671907076),
                                    ("dayminute", -2.2900063107871858),
                                    ("named-day\1489 <date>", -3.270835563798912),
                                    ("absorption of , after named dayintersect",
                                     -3.676300671907076),
                                    ("yearhh:mm", -3.676300671907076),
                                    ("absorption of , after named dayintersect by \",\"",
                                     -3.676300671907076),
                                    ("dayweek", -3.676300671907076),
                                    ("\1502\1512\1509year", -3.270835563798912),
                                    ("\1489 <date>year", -3.676300671907076),
                                    ("absorption of , after named day\1497\1493\1500\1497",
                                     -3.676300671907076),
                                    ("yearminute", -3.676300671907076)],
                               n = 18}}),
       ("year (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next <cycle>",
        Classifier{okData =
                     ClassData{prior = -0.2876820724517809,
                               unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.791759469228055),
                                    ("month (grain)", -1.791759469228055),
                                    ("year (grain)", -1.791759469228055),
                                    ("week (grain)", -1.791759469228055),
                                    ("year", -1.791759469228055), ("month", -1.791759469228055)],
                               n = 3},
                   koData =
                     ClassData{prior = -1.3862943611198906,
                               unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.3862943611198906),
                                    ("week (grain)", -1.3862943611198906)],
                               n = 1}}),
       ("yyyy-mm-dd",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("mm/dd/yyyy",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("evening|night",
        Classifier{okData =
                     ClassData{prior = -0.2876820724517809,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -1.3862943611198906,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("ordinal 3",
        Classifier{okData =
                     ClassData{prior = -0.916290731874155, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -0.5108256237659907,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3}}),
       ("yesterday",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("hh:mm:ss",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month> (ordinal) of <named-month>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinal 3\1502\1512\1509", -2.4849066497880004),
                                    ("ordinal (digits)\1502\1512\1509", -2.0794415416798357),
                                    ("ordinal (digits)\1488\1508\1512\1497\1500",
                                     -2.4849066497880004),
                                    ("ordinal 3\1488\1493\1511\1496\1493\1489\1512",
                                     -2.4849066497880004),
                                    ("month", -0.8754687373538999),
                                    ("ordinal (digits)\1508\1489\1512\1493\1488\1512",
                                     -1.5686159179138452)],
                               n = 9},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<hour-of-day> and <integer>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)integer 4", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1}}),
       ("two weeks",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("quarter to|till|before <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<hour-of-day> <integer>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)integer 10", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1}}),
       ("ordinal 19",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("\1488\1493\1490\1493\1505\1496",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1488\1508\1512\1497\1500",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("week (grain)",
        Classifier{okData =
                     ClassData{prior = -1.791759469228055, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -0.1823215567939546,
                               unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5}}),
       ("now",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer 11..19",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("integer 9integer 10", 0.0)],
                               n = 1}}),
       ("integer 7",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month>(ordinal) <named-month>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.890371757896165,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinal 3\1489 <date>", -1.7346010553881064),
                                    ("ordinal (digits)in <named-month>", -2.1400661634962708),
                                    ("month", -0.8873031950009028),
                                    ("ordinal 3in <named-month>", -1.7346010553881064),
                                    ("ordinal (digits)\1489 <date>", -2.1400661634962708)],
                               n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1497\1493\1500\1497",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("numbers prefix with -, negative or minus",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 6}}),
       ("tomorrow",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3}}),
       ("ordinal 2",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6}}),
       ("next <day-of-week>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.6931471805599453),
                                    ("named-day", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("half an hour",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("fractional number",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 6}}),
       ("this <cycle>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -0.6931471805599453),
                                    ("week (grain)", -0.6931471805599453)],
                               n = 1}}),
       ("minute (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinal 7",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("time-of-day (latent)",
        Classifier{okData =
                     ClassData{prior = -0.8649974374866046,
                               unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.40546510810816444),
                                    ("integer 9", -1.791759469228055)],
                               n = 8},
                   koData =
                     ClassData{prior = -0.5465437063680699, unseen = -2.772588722239781,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.5108256237659907),
                                    ("integer (20..90)", -2.0149030205422647),
                                    ("integer 9", -2.0149030205422647),
                                    ("integer 10", -2.0149030205422647)],
                               n = 11}}),
       ("year",
        Classifier{okData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 8},
                   koData =
                     ClassData{prior = -1.0986122886681098, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 4}}),
       ("integer 9",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("last <day-of-week> of <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods =
                                 HashMap.fromList
                                   [("daymonth", -0.8109302162163288),
                                    ("named-dayintersect", -1.5040773967762742),
                                    ("named-day\1502\1512\1509", -1.0986122886681098)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<integer> <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -0.15415067982725836,
                               unseen = -3.044522437723423,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer 21..99 (with and)hour (grain)", -2.3025850929940455),
                                    ("day", -1.8971199848858813),
                                    ("integer 7day (grain)", -1.8971199848858813),
                                    ("hour", -1.8971199848858813),
                                    ("integer (numeric)minute (grain)", -1.8971199848858813),
                                    ("minute", -1.8971199848858813),
                                    ("integer (numeric)hour (grain)", -2.3025850929940455)],
                               n = 6},
                   koData =
                     ClassData{prior = -1.9459101490553135,
                               unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("hour", -1.6094379124341003),
                                    ("integer 4hour (grain)", -1.6094379124341003)],
                               n = 1}}),
       ("two months",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> am|pm",
        Classifier{okData =
                     ClassData{prior = -0.3513978868378886, unseen = -3.828641396489095,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1489 <date>", -3.1135153092103742),
                                    ("at <time-of-day>", -3.1135153092103742),
                                    ("time-of-day (latent)", -1.8607523407150064),
                                    ("hh:mm", -1.3217558399823195), ("hour", -1.6094379124341003),
                                    ("minute", -1.3217558399823195)],
                               n = 19},
                   koData =
                     ClassData{prior = -1.2163953243244932,
                               unseen = -3.1780538303479458,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -1.0560526742493137),
                                    ("hour", -0.9382696385929302),
                                    ("after <time-of-day>", -2.4423470353692043)],
                               n = 8}}),
       ("integer 10",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("intersect by \",\"",
        Classifier{okData =
                     ClassData{prior = -0.3794896217049037,
                               unseen = -3.7612001156935624,
                               likelihoods =
                                 HashMap.fromList
                                   [("intersect by \",\"year", -3.044522437723423),
                                    ("dayday", -2.128231705849268),
                                    ("named-dayintersect by \",\"", -2.639057329615259),
                                    ("dayyear", -2.128231705849268),
                                    ("<named-month> <day-of-month> (non ordinal)intersect",
                                     -3.044522437723423),
                                    ("named-day<named-month> <day-of-month> (non ordinal)",
                                     -3.044522437723423),
                                    ("intersect by \",\"intersect", -3.044522437723423),
                                    ("named-dayintersect", -3.044522437723423),
                                    ("dayminute", -1.9459101490553135),
                                    ("named-day<day-of-month> (ordinal) of <named-month>",
                                     -3.044522437723423),
                                    ("intersectyear", -3.044522437723423),
                                    ("named-day<day-of-month> (non ordinal) of <named-month>",
                                     -3.044522437723423),
                                    ("intersectintersect", -3.044522437723423),
                                    ("<named-month> <day-of-month> (non ordinal)year",
                                     -2.639057329615259)],
                               n = 13},
                   koData =
                     ClassData{prior = -1.1526795099383855, unseen = -3.367295829986474,
                               likelihoods =
                                 HashMap.fromList
                                   [("daymonth", -2.639057329615259),
                                    ("named-dayintersect by \",\"", -2.639057329615259),
                                    ("named-day\1497\1493\1500\1497", -2.639057329615259),
                                    ("<named-month> <day-of-month> (non ordinal)intersect",
                                     -2.639057329615259),
                                    ("intersect by \",\"intersect", -2.639057329615259),
                                    ("named-dayintersect", -2.639057329615259),
                                    ("dayminute", -1.540445040947149),
                                    ("intersectintersect", -2.639057329615259)],
                               n = 6}}),
       ("hh:mm",
        Classifier{okData =
                     ClassData{prior = -7.410797215372185e-2,
                               unseen = -2.70805020110221,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 13},
                   koData =
                     ClassData{prior = -2.639057329615259, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("named-day",
        Classifier{okData =
                     ClassData{prior = -7.696104113612832e-2,
                               unseen = -3.295836866004329,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 25},
                   koData =
                     ClassData{prior = -2.6026896854443837,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("ordinal 1",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7}}),
       ("current <day-of-week>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1489 <date>", -1.9459101490553135),
                                    ("\1489 <named-day>", -1.9459101490553135),
                                    ("day", -0.8472978603872037),
                                    ("named-day", -1.252762968495368)],
                               n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer 4",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("quarter of an hour",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<named-day> <day-of-month> (ordinal)",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("named-dayordinal (digits)", -0.916290731874155),
                                    ("day", -0.916290731874155)],
                               n = 1},
                   koData =
                     ClassData{prior = -0.6931471805599453, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("absorption of , after named dayordinal (digits)",
                                     -0.916290731874155),
                                    ("day", -0.916290731874155)],
                               n = 1}}),
       ("a week",
        Classifier{okData =
                     ClassData{prior = -2.1972245773362196,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -0.11778303565638351,
                               unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8}}),
       ("<duration> ago",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.6931471805599453),
                                    ("<integer> <unit-of-duration>", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinal 6",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4}}),
       ("integer 3",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("last <time>",
        Classifier{okData =
                     ClassData{prior = -0.9808292530117262,
                               unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1489 <date>", -1.791759469228055),
                                    ("day", -1.791759469228055), ("named-day", -1.791759469228055),
                                    ("hour", -1.3862943611198906),
                                    ("week-end", -1.791759469228055)],
                               n = 3},
                   koData =
                     ClassData{prior = -0.4700036292457356, unseen = -2.833213344056216,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.9808292530117262),
                                    ("named-day", -1.6739764335716716),
                                    ("<day-of-month> (ordinal)", -1.3862943611198906)],
                               n = 5}}),
       ("<day-of-month> (ordinal)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.4849066497880004,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinal 4", -1.7047480922384253),
                                    ("ordinal 3", -1.7047480922384253),
                                    ("ordinal 2", -1.0116009116784799),
                                    ("ordinal 1", -1.2992829841302609)],
                               n = 7}}),
       ("\1488\1493\1511\1496\1493\1489\1512",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("this morning",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("noon",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("\1508\1489\1512\1493\1488\1512",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next <time>",
        Classifier{okData =
                     ClassData{prior = -1.3862943611198906,
                               unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1502\1512\1509", -1.0986122886681098),
                                    ("month", -1.0986122886681098)],
                               n = 1},
                   koData =
                     ClassData{prior = -0.2876820724517809,
                               unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.916290731874155), ("named-day", -0.916290731874155)],
                               n = 3}}),
       ("last <cycle>",
        Classifier{okData =
                     ClassData{prior = -1.3862943611198906,
                               unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("month (grain)", -1.0986122886681098),
                                    ("month", -1.0986122886681098)],
                               n = 1},
                   koData =
                     ClassData{prior = -0.2876820724517809,
                               unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -0.916290731874155),
                                    ("week (grain)", -0.916290731874155)],
                               n = 3}}),
       ("ordinal 20..90",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("hhmm (military) am|pm",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("in <duration>",
        Classifier{okData =
                     ClassData{prior = -0.2231435513142097,
                               unseen = -3.6109179126442243,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.1972245773362196),
                                    ("two weeks", -2.4849066497880004), ("day", -2.890371757896165),
                                    ("half an hour", -2.890371757896165),
                                    ("<integer> <unit-of-duration>", -1.791759469228055),
                                    ("two months", -2.890371757896165),
                                    ("quarter of an hour", -2.890371757896165),
                                    ("a week", -2.890371757896165), ("hour", -2.4849066497880004),
                                    ("month", -2.4849066497880004), ("minute", -1.9740810260220096),
                                    ("a month", -2.890371757896165)],
                               n = 12},
                   koData =
                     ClassData{prior = -1.6094379124341003,
                               unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.791759469228055), ("a week", -1.791759469228055),
                                    ("month", -2.1972245773362196),
                                    ("a month", -2.1972245773362196)],
                               n = 3}}),
       ("in <named-month>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1502\1512\1509", -1.3862943611198906),
                                    ("\1488\1493\1511\1496\1493\1489\1512", -1.791759469228055),
                                    ("month", -0.8754687373538999),
                                    ("\1508\1489\1512\1493\1488\1512", -1.791759469228055)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinal 5",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("<named-month> <day-of-month> (non ordinal)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.1354942159291497,
                               likelihoods =
                                 HashMap.fromList
                                   [("in <named-month>integer (numeric)", -2.3978952727983707),
                                    ("\1502\1512\1509integer (numeric)", -2.3978952727983707),
                                    ("\1489 <date>integer (numeric)", -2.3978952727983707),
                                    ("\1508\1489\1512\1493\1488\1512integer (numeric)",
                                     -2.3978952727983707),
                                    ("\1488\1493\1490\1493\1505\1496integer (numeric)",
                                     -2.3978952727983707),
                                    ("\1488\1508\1512\1497\1500integer (numeric)",
                                     -2.3978952727983707),
                                    ("\1497\1493\1500\1497integer (numeric)", -2.3978952727983707),
                                    ("month", -1.0116009116784799)],
                               n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month> (non ordinal) <named-month>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.639057329615259,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)in <named-month>", -1.8718021769015913),
                                    ("integer 3\1489 <date>", -1.8718021769015913),
                                    ("integer (numeric)\1489 <date>", -1.8718021769015913),
                                    ("month", -0.9555114450274363),
                                    ("integer 3in <named-month>", -1.8718021769015913)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("ordinal (digits)",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7}}),
       ("<day-of-month>(ordinal) <named-month> year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("ordinal 3\1489 <date>", -1.252762968495368),
                                    ("month", -0.8472978603872037),
                                    ("ordinal 3in <named-month>", -1.252762968495368)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this noon",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("morning",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("week-end",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this evening",
        Classifier{okData =
                     ClassData{prior = -0.916290731874155, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -0.5108256237659907,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3}}),
       ("after <time-of-day>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -2.0794415416798357,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -1.252762968495368),
                                    ("<time-of-day> am|pm", -1.252762968495368),
                                    ("hour", -0.8472978603872037)],
                               n = 2}}),
       ("day (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("day after tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("a month",
        Classifier{okData =
                     ClassData{prior = -1.3862943611198906,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -0.2876820724517809,
                               unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3}}),
       ("this <time>",
        Classifier{okData =
                     ClassData{prior = -0.45198512374305727,
                               unseen = -3.0910424533583156,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1489 <date>", -1.9459101490553135),
                                    ("\1489 <named-day>", -2.3513752571634776),
                                    ("day", -1.252762968495368), ("named-day", -1.6582280766035324),
                                    ("hour", -1.9459101490553135),
                                    ("week-end", -2.3513752571634776)],
                               n = 7},
                   koData =
                     ClassData{prior = -1.0116009116784799, unseen = -2.772588722239781,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1489 <date>", -2.0149030205422647),
                                    ("day", -1.0986122886681098),
                                    ("<day-of-month> (ordinal)", -1.3217558399823195)],
                               n = 4}})]