-- Copyright (c) 2016-present, Facebook, Inc.
-- All rights reserved.
--
-- This source code is licensed under the BSD-style license found in the
-- LICENSE file in the root directory of this source tree. An additional grant
-- of patent rights can be found in the PATENTS file in the same directory.

-----------------------------------------------------------------
-- Auto-generated by regenClassifiers
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
module Duckling.Ranking.Classifiers.ZH_MO (classifiers) where
import Data.String
import Prelude
import qualified Data.HashMap.Strict as HashMap
import Duckling.Ranking.Types

classifiers :: Classifiers
classifiers
  = HashMap.fromList
      [("<time> timezone",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time-of-day> am|pm", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Thursday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer (numeric)",
        Classifier{okData =
                     ClassData{prior = -0.5020919437972361, unseen = -3.871201010907891,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 46},
                   koData =
                     ClassData{prior = -0.9295359586241757,
                               unseen = -3.4657359027997265,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 30}}),
       ("the day before yesterday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\22269\38469\28040\36153\32773\26435\30410\26085",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\24314\20891\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("today",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("mm/dd",
        Classifier{okData =
                     ClassData{prior = -1.6094379124341003,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -0.2231435513142097, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4}}),
       ("absorption of , after named day",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.833213344056216,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.6931471805599453), ("Sunday", -0.6931471805599453)],
                               n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("tonight",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("October",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("month (grain)",
        Classifier{okData =
                     ClassData{prior = -1.0076405104623831,
                               unseen = -3.2188758248682006,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 23},
                   koData =
                     ClassData{prior = -0.45425527227759643,
                               unseen = -3.7376696182833684,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 40}}),
       ("<time-of-day> o'clock",
        Classifier{okData =
                     ClassData{prior = -0.4418327522790392, unseen = -3.044522437723423,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 9},
                   koData =
                     ClassData{prior = -1.0296194171811581,
                               unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 5}}),
       ("national day",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("number suffix: \21313",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.258096538021482,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 24},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Wednesday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.9444389791664407,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 17},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hour (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.0910424533583156,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 20},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\20803\26086",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("intersect",
        Classifier{okData =
                     ClassData{prior = -0.3519764231571781, unseen = -4.983606621708336,
                               likelihoods =
                                 HashMap.fromList
                                   [("\20799\31461\33410<part-of-day> <dim time>",
                                     -3.367295829986474),
                                    ("year (numeric with year symbol)<named-month> <day-of-month>",
                                     -1.7578579175523736),
                                    ("dayday", -1.6094379124341003),
                                    ("hourhour", -3.367295829986474),
                                    ("hourminute", -3.367295829986474),
                                    ("absorption of , after named day<named-month> <day-of-month>",
                                     -1.6094379124341003),
                                    ("dayminute", -3.367295829986474),
                                    ("tonight<time-of-day> o'clock", -3.367295829986474),
                                    ("<dim time> <part-of-day>relative minutes after|past <integer> (hour-of-day)",
                                     -3.367295829986474),
                                    ("yearday", -1.7578579175523736)],
                               n = 64},
                   koData =
                     ClassData{prior = -1.215022640512521, unseen = -4.276666119016055,
                               likelihoods =
                                 HashMap.fromList
                                   [("\20799\31461\33410<part-of-day> <dim time>",
                                     -2.065455299705096),
                                    ("dayhour", -2.653241964607215),
                                    ("daymonth", -2.1832383353614793),
                                    ("year (numeric with year symbol)February", -3.164067588373206),
                                    ("<dim time> <part-of-day><time-of-day> o'clock",
                                     -3.164067588373206),
                                    ("hourhour", -3.164067588373206),
                                    ("year (numeric with year symbol)March", -2.653241964607215),
                                    ("hourminute", -2.653241964607215),
                                    ("yearmonth", -2.316769727986002),
                                    ("dayminute", -2.653241964607215),
                                    ("<dim time> <part-of-day>relative minutes after|past <integer> (hour-of-day)",
                                     -2.653241964607215),
                                    ("absorption of , after named dayFebruary",
                                     -2.1832383353614793)],
                               n = 27}}),
       ("year (grain)",
        Classifier{okData =
                     ClassData{prior = -0.8209805520698302,
                               unseen = -2.5649493574615367,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 11},
                   koData =
                     ClassData{prior = -0.579818495252942, unseen = -2.772588722239781,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 14}}),
       ("Saturday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next <cycle>",
        Classifier{okData =
                     ClassData{prior = -1.55814461804655, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("month (grain)", -1.252762968495368),
                                    ("year (grain)", -1.9459101490553135),
                                    ("year", -1.9459101490553135), ("month", -1.252762968495368)],
                               n = 4},
                   koData =
                     ClassData{prior = -0.2363887780642304,
                               unseen = -3.6109179126442243,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -0.8109302162163288),
                                    ("week (grain)", -0.8109302162163288)],
                               n = 15}}),
       ("last year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this <day-of-week>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.970291913552122,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -1.8718021769015913),
                                    ("Monday", -1.8718021769015913), ("day", -0.7323678937132265),
                                    ("Tuesday", -1.5533484457830569)],
                               n = 24},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("yyyy-mm-dd",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("mm/dd/yyyy",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("evening|night",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Monday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.258096538021482,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 24},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("yesterday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hh:mm (time-of-day)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<integer> (latent time-of-day)",
        Classifier{okData =
                     ClassData{prior = -1.4170660197866443, unseen = -2.995732273553991,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -1.3350010667323402),
                                    ("integer (0..10)", -0.3794896217049037)],
                               n = 16},
                   koData =
                     ClassData{prior = -0.2776317365982795,
                               unseen = -3.9889840465642745,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -2.3608540011180215),
                                    ("integer (0..10)", -0.28141245943818544),
                                    ("<number>\20010/\20491", -1.890850371872286)],
                               n = 50}}),
       ("nth <time> of <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.332204510175204,
                               likelihoods =
                                 HashMap.fromList
                                   [("Octoberordinal (digits)Monday", -1.6863989535702288),
                                    ("monthday", -0.7308875085427924),
                                    ("month (numeric with month symbol)ordinal (digits)Monday",
                                     -1.0986122886681098)],
                               n = 12},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("month (numeric with month symbol)",
        Classifier{okData =
                     ClassData{prior = -0.10763066419236544,
                               unseen = -3.891820298110627,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -1.1631508098056809),
                                    ("number suffix: \21313", -2.2617630984737906),
                                    ("integer (0..10)", -0.5753641449035618)],
                               n = 44},
                   koData =
                     ClassData{prior = -2.2823823856765264,
                               unseen = -2.3025850929940455,
                               likelihoods =
                                 HashMap.fromList [("<number>\20010/\20491", -0.40546510810816444)],
                               n = 5}}),
       ("week (grain)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -4.477336814478207,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 86}}),
       ("year (numeric with year symbol)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.772588722239781,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 14},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("now",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\24858\20154\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("numbers prefix with -, negative or minus",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 4}}),
       ("Friday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\28595\38376\22238\24402\32426\24565\26085",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next <day-of-week>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.1780538303479458,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -1.3437347467010947),
                                    ("day", -0.7375989431307791), ("Tuesday", -1.3437347467010947)],
                               n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("fractional number",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5}}),
       ("Sunday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.0910424533583156,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 20},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("afternoon",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 9},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<duration> from now",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -3.891820298110627,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.2617630984737906), ("second", -2.772588722239781),
                                    ("day", -2.2617630984737906), ("year", -2.772588722239781),
                                    ("<integer> <unit-of-duration>", -0.8266785731844679),
                                    ("hour", -2.2617630984737906), ("month", -2.772588722239781),
                                    ("minute", -2.772588722239781)],
                               n = 20}}),
       ("February",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.833213344056216,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 15},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this <cycle>",
        Classifier{okData =
                     ClassData{prior = -2.890371757896165, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("year (grain)", -0.9808292530117262),
                                    ("year", -0.9808292530117262)],
                               n = 2},
                   koData =
                     ClassData{prior = -5.715841383994864e-2,
                               unseen = -4.290459441148391,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -0.7213180575266417),
                                    ("week (grain)", -0.7213180575266417)],
                               n = 34}}),
       ("minute (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.890371757896165,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 16},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<dim time> <part-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.31748811353631,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayhour", -0.7487170317147561),
                                    ("national dayevening|night", -3.20545280453606),
                                    ("<named-month> <day-of-month>morning", -1.2595426554807467),
                                    ("\24773\20154\33410evening|night", -3.20545280453606),
                                    ("\20799\31461\33410afternoon", -3.20545280453606),
                                    ("Mondaymorning", -2.10684051586795)],
                               n = 34},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<part-of-day> <dim time>",
        Classifier{okData =
                     ClassData{prior = -0.6097655716208943, unseen = -4.07753744390572,
                               likelihoods =
                                 HashMap.fromList
                                   [("tonight<integer> (latent time-of-day)", -2.451005098112319),
                                    ("hourhour", -1.3523928094442093),
                                    ("afternoonrelative minutes after|past <integer> (hour-of-day)",
                                     -1.6625477377480489),
                                    ("afternoon<time-of-day> o'clock", -2.6741486494265287),
                                    ("hourminute", -1.575536360758419),
                                    ("afternoon<integer> (latent time-of-day)",
                                     -2.6741486494265287),
                                    ("afternoonhh:mm (time-of-day)", -3.367295829986474),
                                    ("tonight<time-of-day> o'clock", -2.451005098112319)],
                               n = 25},
                   koData =
                     ClassData{prior = -0.7841189587656721,
                               unseen = -3.9318256327243257,
                               likelihoods =
                                 HashMap.fromList
                                   [("hourhour", -1.4271163556401458),
                                    ("afternoonrelative minutes after|past <integer> (hour-of-day)",
                                     -1.5141277326297755),
                                    ("afternoon<time-of-day> o'clock", -2.120263536200091),
                                    ("hourminute", -1.5141277326297755),
                                    ("afternoon<integer> (latent time-of-day)",
                                     -1.9661128563728327)],
                               n = 21}}),
       ("<integer> <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -3.044522437723423,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -5.905361848054571,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.6837575085331653),
                                    ("integer (0..10)month (grain)", -2.535337503414892),
                                    ("integer (0..10)hour (grain)", -3.06941998934515),
                                    ("<number>\20010/\20491week (grain)", -3.5047380606029956),
                                    ("second", -3.2635760037861075),
                                    ("integer (0..10)day (grain)", -3.06941998934515),
                                    ("number suffix: \21313month (grain)", -4.293195420967266),
                                    ("integer (0..10)year (grain)", -3.6000482404073204),
                                    ("<number>\20010/\20491month (grain)", -3.130044611161585),
                                    ("integer (numeric)year (grain)", -3.1945831322991562),
                                    ("integer (0..10)second (grain)", -3.2635760037861075),
                                    ("day", -3.06941998934515), ("year", -2.7245795030534206),
                                    ("integer (0..10)minute (grain)", -3.06941998934515),
                                    ("hour", -2.8581108956779433),
                                    ("integer (0..10)week (grain)", -3.1945831322991562),
                                    ("month", -1.7754989483562746),
                                    ("<number>\20010/\20491hour (grain)", -4.293195420967266),
                                    ("integer (numeric)month (grain)", -3.1945831322991562),
                                    ("minute", -3.06941998934515)],
                               n = 173}}),
       ("<time-of-day> am|pm",
        Classifier{okData =
                     ClassData{prior = -0.4700036292457356, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("hh:mm (time-of-day)", -1.252762968495368),
                                    ("<integer> (latent time-of-day)", -1.540445040947149),
                                    ("hour", -1.540445040947149), ("minute", -1.252762968495368)],
                               n = 5},
                   koData =
                     ClassData{prior = -0.9808292530117262,
                               unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.916290731874155),
                                    ("hour", -0.916290731874155)],
                               n = 3}}),
       ("number suffix: \19975",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("relative minutes after|past <integer> (hour-of-day)",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)integer with consecutive unit modifiers",
                                     -0.7801585575495751),
                                    ("hour", -0.7801585575495751)],
                               n = 10},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)number suffix: \21313",
                                     -1.3862943611198906),
                                    ("<integer> (latent time-of-day)integer (0..10)",
                                     -1.3862943611198906),
                                    ("hour", -0.7801585575495751)],
                               n = 10}}),
       ("intersect by \",\"",
        Classifier{okData =
                     ClassData{prior = -0.2231435513142097, unseen = -4.110873864173311,
                               likelihoods =
                                 HashMap.fromList
                                   [("Sunday<named-month> <day-of-month>", -0.7270487322356266),
                                    ("dayday", -0.7270487322356266)],
                               n = 28},
                   koData =
                     ClassData{prior = -1.6094379124341003,
                               unseen = -2.9444389791664407,
                               likelihoods =
                                 HashMap.fromList
                                   [("daymonth", -0.8109302162163288),
                                    ("SundayFebruary", -0.8109302162163288)],
                               n = 7}}),
       ("integer with consecutive unit modifiers",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.367295829986474,
                               likelihoods =
                                 HashMap.fromList
                                   [("number suffix: \21313integer (0..10)", -0.6931471805599453),
                                    ("integer (0..10)integer (0..10)", -0.6931471805599453)],
                               n = 26},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("second (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 13},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<duration> ago",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -3.891820298110627,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.2617630984737906), ("second", -2.772588722239781),
                                    ("day", -2.2617630984737906), ("year", -2.772588722239781),
                                    ("<integer> <unit-of-duration>", -0.8266785731844679),
                                    ("hour", -2.2617630984737906), ("month", -2.772588722239781),
                                    ("minute", -2.772588722239781)],
                               n = 20}}),
       ("\22307\35806\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("last <time>",
        Classifier{okData =
                     ClassData{prior = -1.2286654169163076,
                               unseen = -3.4657359027997265,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -0.8690378470236094), ("Sunday", -1.3545456628053103),
                                    ("Tuesday", -1.6422277352570913)],
                               n = 12},
                   koData =
                     ClassData{prior = -0.3462762367178338, unseen = -4.189654742026425,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.916290731874155),
                                    ("month (numeric with month symbol)", -2.5649493574615367),
                                    ("hour", -0.916290731874155), ("month", -2.5649493574615367)],
                               n = 29}}),
       ("March",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("the day after tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\22919\22899\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("next <time>",
        Classifier{okData =
                     ClassData{prior = -1.6486586255873816, unseen = -2.890371757896165,
                               likelihoods =
                                 HashMap.fromList
                                   [("day", -1.041453874828161), ("Tuesday", -1.041453874828161)],
                               n = 5},
                   koData =
                     ClassData{prior = -0.21357410029805904,
                               unseen = -3.912023005428146,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -2.1000608288825715),
                                    ("<integer> (latent time-of-day)", -1.1192315758708455),
                                    ("month (numeric with month symbol)", -3.1986731175506815),
                                    ("day", -2.1000608288825715), ("hour", -1.1192315758708455),
                                    ("month", -3.1986731175506815)],
                               n = 21}}),
       ("last <cycle>",
        Classifier{okData =
                     ClassData{prior = -1.6582280766035324, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("month (grain)", -1.252762968495368),
                                    ("year (grain)", -1.9459101490553135),
                                    ("year", -1.9459101490553135), ("month", -1.252762968495368)],
                               n = 4},
                   koData =
                     ClassData{prior = -0.2113090936672069, unseen = -3.713572066704308,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -0.7985076962177716),
                                    ("week (grain)", -0.7985076962177716)],
                               n = 17}}),
       ("next n <cycle>",
        Classifier{okData =
                     ClassData{prior = -0.2113090936672069, unseen = -4.442651256490317,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (0..10)hour (grain)", -2.4849066497880004),
                                    ("second", -2.639057329615259),
                                    ("integer (0..10)day (grain)", -2.3513752571634776),
                                    ("integer (0..10)year (grain)", -3.044522437723423),
                                    ("<number>\20010/\20491month (grain)", -2.639057329615259),
                                    ("integer (0..10)second (grain)", -2.639057329615259),
                                    ("day", -2.3513752571634776), ("year", -3.044522437723423),
                                    ("integer (0..10)minute (grain)", -2.4849066497880004),
                                    ("hour", -2.2335922215070942), ("month", -2.639057329615259),
                                    ("<number>\20010/\20491hour (grain)", -3.332204510175204),
                                    ("minute", -2.4849066497880004)],
                               n = 34},
                   koData =
                     ClassData{prior = -1.6582280766035324,
                               unseen = -3.4965075614664802,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.2685113254635072),
                                    ("<number>\20010/\20491week (grain)", -1.8562979903656263),
                                    ("integer (0..10)week (grain)", -1.8562979903656263)],
                               n = 8}}),
       ("\19975\22307\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\20799\31461\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Tuesday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.295836866004329,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 25},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<named-month> <day-of-month>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -5.231108616854587,
                               likelihoods =
                                 HashMap.fromList
                                   [("month (numeric with month symbol)integer with consecutive unit modifiers",
                                     -2.392533329656985),
                                    ("Marchinteger (0..10)", -3.4339872044851463),
                                    ("Marchinteger (numeric)", -4.127134385045092),
                                    ("month (numeric with month symbol)integer (numeric)",
                                     -2.517696472610991),
                                    ("Februaryinteger (0..10)", -3.146305132033365),
                                    ("month (numeric with month symbol)number suffix: \21313",
                                     -3.146305132033365),
                                    ("month", -0.7371103039810614),
                                    ("month (numeric with month symbol)integer (0..10)",
                                     -2.517696472610991),
                                    ("Februaryinteger with consecutive unit modifiers",
                                     -2.392533329656985),
                                    ("Februarynumber suffix: \21313", -3.146305132033365)],
                               n = 88},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\21171\21160\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer (0..10)",
        Classifier{okData =
                     ClassData{prior = -0.4989911661189879, unseen = -5.147494476813453,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 170},
                   koData =
                     ClassData{prior = -0.9343092373768334, unseen = -4.718498871295094,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 110}}),
       ("last n <cycle>",
        Classifier{okData =
                     ClassData{prior = -0.10008345855698253,
                               unseen = -4.5217885770490405,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (0..10)month (grain)", -3.41224721784874),
                                    ("integer (0..10)hour (grain)", -2.3136349291806306),
                                    ("second", -2.5649493574615367),
                                    ("integer (0..10)day (grain)", -2.9014215940827497),
                                    ("integer (0..10)year (grain)", -3.41224721784874),
                                    ("<number>\20010/\20491month (grain)", -2.3136349291806306),
                                    ("integer (0..10)second (grain)", -2.5649493574615367),
                                    ("day", -2.9014215940827497), ("year", -3.41224721784874),
                                    ("integer (0..10)minute (grain)", -2.3136349291806306),
                                    ("hour", -2.3136349291806306), ("month", -2.1129642337184795),
                                    ("minute", -2.3136349291806306)],
                               n = 38},
                   koData =
                     ClassData{prior = -2.3513752571634776,
                               unseen = -3.1780538303479458,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.5260563034950494),
                                    ("integer (0..10)week (grain)", -1.5260563034950494)],
                               n = 4}}),
       ("ordinal (digits)",
        Classifier{okData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList [("<number>\20010/\20491", -0.1823215567939546)],
                               n = 4},
                   koData =
                     ClassData{prior = -0.6931471805599453,
                               unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList [("integer (0..10)", -0.1823215567939546)],
                               n = 4}}),
       ("n <cycle> last",
        Classifier{okData =
                     ClassData{prior = -0.2231435513142097, unseen = -3.891820298110627,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (0..10)hour (grain)", -2.772588722239781),
                                    ("second", -2.772588722239781),
                                    ("integer (0..10)day (grain)", -2.2617630984737906),
                                    ("integer (0..10)year (grain)", -2.772588722239781),
                                    ("<number>\20010/\20491month (grain)", -2.772588722239781),
                                    ("integer (0..10)second (grain)", -2.772588722239781),
                                    ("day", -2.2617630984737906), ("year", -2.772588722239781),
                                    ("integer (0..10)minute (grain)", -2.772588722239781),
                                    ("hour", -2.2617630984737906), ("month", -2.772588722239781),
                                    ("<number>\20010/\20491hour (grain)", -2.772588722239781),
                                    ("minute", -2.772588722239781)],
                               n = 16},
                   koData =
                     ClassData{prior = -1.6094379124341003,
                               unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.5686159179138452),
                                    ("<number>\20010/\20491week (grain)", -2.0794415416798357),
                                    ("integer (0..10)week (grain)", -2.0794415416798357)],
                               n = 4}}),
       ("morning",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.890371757896165,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 16},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("week-end",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("day (grain)",
        Classifier{okData =
                     ClassData{prior = -6.453852113757118e-2,
                               unseen = -2.833213344056216,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 15},
                   koData =
                     ClassData{prior = -2.772588722239781, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("<number>\20010/\20491",
        Classifier{okData =
                     ClassData{prior = -0.2318016140573243,
                               unseen = -3.2188758248682006,
                               likelihoods = HashMap.fromList [("integer (0..10)", 0.0)], n = 23},
                   koData =
                     ClassData{prior = -1.575536360758419, unseen = -2.0794415416798357,
                               likelihoods = HashMap.fromList [("integer (0..10)", 0.0)],
                               n = 6}}),
       ("\24773\20154\33410",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("this <time>",
        Classifier{okData =
                     ClassData{prior = -0.2076393647782445, unseen = -4.0943445622221,
                               likelihoods =
                                 HashMap.fromList
                                   [("Wednesday", -1.9980959022258835),
                                    ("Monday", -1.9980959022258835), ("day", -0.8586616190375187),
                                    ("hour", -2.9789251552376097), ("Tuesday", -1.6796421711073488),
                                    ("week-end", -2.9789251552376097)],
                               n = 26},
                   koData =
                     ClassData{prior = -1.6739764335716716, unseen = -2.995732273553991,
                               likelihoods =
                                 HashMap.fromList
                                   [("<integer> (latent time-of-day)", -0.9985288301111273),
                                    ("hour", -0.9985288301111273)],
                               n = 6}})]